!function (e) {
    const t = e.zh = e.zh || {}; t.dictionary = Object.assign(t.dictionary || {}, {
        "%0 of %1": "%0/%1",
        "Break text": "",
        "Bulleted List": "項目符號",
        "Cannot upload file:": "無法上傳檔案：",
        "Choose heading": "選取標題",
        Column: "欄",
        "Dropdown toolbar": "下拉選單",
        "Font Background Color": "背景顏色",
        "In line": "",
        "Numbered List": "編號",
        Paragraph: "段落",
        // Redo: "取消復原",
        "Rich Text Editor": "豐富文字編輯器",
        "Rich Text Editor, %0": "豐富文字編輯器，%0",
        "Table toolbar": "表格工具",
        // Undo: "復原",
        "Insert table": "插入表格",
        "Header column": "標題欄",
        "Header row": "標題列",
        "Delete column": "刪除欄",
        "Delete row": "刪除列",
        "Insert column left": "插入左方欄",
        "Insert column right": "插入右方欄",
        "Insert row above": "插入上方列",
        "Insert row below": "插入下方列",
        "Centered image": "置中圖片",
        "Change image text alternative": "修改圖片的替代文字",
        "Could not insert image at the current position.": "無法在這位置插入圖片",
        "Could not obtain resized image URL.": "無法取得重設大小的圖片URL",
        "Full size image": "完整尺寸圖片",
        "Enter image caption": "輸入圖片說明",
        "Image toolbar": "圖片工具",
        "image widget": "圖片小工具",
        "Insert image": "插入圖片",
        "Insert image or file": "插入圖片或檔案",
        "Insert media": "插入影音",
        Row: "列",
        "Merge cell down": "合併下方儲存格",
        "Merge cell left": "合併左方儲存格",
        "Merge cell right": "合併右方儲存格",
        "Merge cell up": "合併上方儲存格",
        "Merge cells": "合併儲存格",
        "Select column": "選擇欄",
        "Select row": "選擇列",
        "Split cell horizontally": "水平分割儲存格",
        "Split cell vertically": "垂直分割儲存格",
        "Text alternative": "替代文字",
        "The URL must not be empty.": "網址不能空白。",
        "This link has no URL": "連結沒有URL",
        "Paste the media URL in the input.": "在輸入框貼上影音網址。",
        "This media URL is not supported.": "不支援此影音網址。",
        "Tip: Paste the URL into the content to embed faster.": "提示：在內容貼上網址更快崁入。",
        "Toggle caption off": "關閉表標題",
        "Toggle caption on": "開啟表標題",
        "Selecting resized image failed": "選擇重設大小的圖片失敗",
        "Inserting image failed": "插入圖片失敗",
        "Left aligned image": "向左對齊圖片",
        "Media URL": "影音網址",
        "media widget": "影音小工具",
        "Right aligned image": "向右對齊圖片",
        "Side image": "側邊圖片",
        "Upload failed": "上傳失敗",
        "Upload in progress": "正在上傳",
    }), t.getPluralForm = function (e) { return 0 }
}(window.CKEDITOR_TRANSLATIONS || (window.CKEDITOR_TRANSLATIONS = {}));